In [1]:
import pandas as pd
pd.set_option('display.max_columns', 250)
# Don't cut off long string
# http://stackoverflow.com/questions/26277757/pandas-to-html-truncates-string-contents
pd.set_option('display.max_colwidth', -1)


from IPython.display import display

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

# Extracting mapping information from annotation

In [2]:
ndf1 = pd.read_pickle('../download/ensembl/Homo_sapiens.GRCh37.75.pkl')

In [3]:
_cols = ndf1.columns.tolist()
for k, i in enumerate(_cols):
    if k % 3 == 0 and k > 0:
        print()
    print('{0:2d} {1:28s}'.format(k + 1, i), end='')

 1 seqname                      2 source                       3 feature
 4 start                        5 end                          6 score
 7 strand                       8 frame                        9 ccds_id
10 exon_id                     11 exon_number                 12 gene_biotype
13 gene_id                     14 gene_name                   15 gene_source
16 protein_id                  17 tag:CCDS                    18 tag:cds_end_NF
19 tag:cds_start_NF            20 tag:mRNA_end_NF             21 tag:mRNA_start_NF
22 tag:seleno                  23 transcript_id               24 transcript_name
25 transcript_source

In [4]:
ndf1.head()

,seqname,source,feature,start,end,score,strand,frame,ccds_id,exon_id,exon_number,gene_biotype,gene_id,gene_name,gene_source,protein_id,tag:CCDS,tag:cds_end_NF,tag:cds_start_NF,tag:mRNA_end_NF,tag:mRNA_start_NF,tag:seleno,transcript_id,transcript_name,transcript_source
0,1,pseudogene,gene,11869,14412,.,+,.,NaN,NaN,NaN,pseudogene,ENSG00000223972,DDX11L1,ensembl_havana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,processed_transcript,transcript,11869,14409,.,+,.,NaN,NaN,NaN,pseudogene,ENSG00000223972,DDX11L1,ensembl_havana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000456328,DDX11L1-002,havana
2,1,processed_transcript,exon,11869,12227,.,+,.,NaN,ENSE00002234944,1,pseudogene,ENSG00000223972,DDX11L1,ensembl_havana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000456328,DDX11L1-002,havana
3,1,processed_transcript,exon,12613,12721,.,+,.,NaN,ENSE00003582793,2,pseudogene,ENSG00000223972,DDX11L1,ensembl_havana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000456328,DDX11L1-002,havana
4,1,processed_transcript,exon,13221,14409,.,+,.,NaN,ENSE00002312635,3,pseudogene,ENSG00000223972,DDX11L1,ensembl_havana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000456328,DDX11L1-002,havana

In [5]:
ndf2 = pd.read_pickle('../download/ensembl/Homo_sapiens.GRCh38.93.pkl')

In [6]:
_cols = ndf2.columns.tolist()
for k, i in enumerate(_cols):
    if k % 3 == 0 and k > 0:
        print()
    print('{0:2d} {1:28s}'.format(k + 1, i), end='')

 1 seqname                      2 source                       3 feature
 4 start                        5 end                          6 score
 7 strand                       8 frame                        9 ccds_id
10 exon_id                     11 exon_number                 12 exon_version
13 gene_biotype                14 gene_id                     15 gene_name
16 gene_source                 17 gene_version                18 protein_id
19 protein_version             20 tag:CCDS                    21 tag:basic
22 tag:cds_end_NF              23 tag:cds_start_NF            24 tag:mRNA_end_NF
25 tag:mRNA_start_NF           26 tag:seleno                  27 transcript_biotype
28 transcript_id               29 transcript_name             30 transcript_source
31 transcript_support_level    32 transcript_version

In [7]:
s1 = set(ndf1.columns.values)
s2 = set(ndf2.columns.values)

In [8]:
s1.difference(s2)

set()

In [9]:
for i in sorted(s2.difference(s1)):print(i)

exon_version
gene_version
protein_version
tag:basic
transcript_biotype
transcript_support_level
transcript_version

# Debug

In [10]:
ndf2.head().fillna('')

,seqname,source,feature,start,end,score,strand,frame,ccds_id,exon_id,exon_number,exon_version,gene_biotype,gene_id,gene_name,gene_source,gene_version,protein_id,protein_version,tag:CCDS,tag:basic,tag:cds_end_NF,tag:cds_start_NF,tag:mRNA_end_NF,tag:mRNA_start_NF,tag:seleno,transcript_biotype,transcript_id,transcript_name,transcript_source,transcript_support_level,transcript_version
0,1,havana,gene,11869,14409,.,+,.,,,,,transcribed_unprocessed_pseudogene,ENSG00000223972,DDX11L1,havana,5,,,,,,,,,,,,,,,
1,1,havana,transcript,11869,14409,.,+,.,,,,,transcribed_unprocessed_pseudogene,ENSG00000223972,DDX11L1,havana,5,,,,1,,,,,,processed_transcript,ENST00000456328,DDX11L1-202,havana,1,2
2,1,havana,exon,11869,12227,.,+,.,,ENSE00002234944,1,1,transcribed_unprocessed_pseudogene,ENSG00000223972,DDX11L1,havana,5,,,,1,,,,,,processed_transcript,ENST00000456328,DDX11L1-202,havana,1,2
3,1,havana,exon,12613,12721,.,+,.,,ENSE00003582793,2,1,transcribed_unprocessed_pseudogene,ENSG00000223972,DDX11L1,havana,5,,,,1,,,,,,processed_transcript,ENST00000456328,DDX11L1-202,havana,1,2
4,1,havana,exon,13221,14409,.,+,.,,ENSE00002312635,3,1,transcribed_unprocessed_pseudogene,ENSG00000223972,DDX11L1,havana,5,,,,1,,,,,,processed_transcript,ENST00000456328,DDX11L1-202,havana,1,2